
"""Revision ID: d475c6a21698
Revises: 0001_initial
Create Date: 2025-08-31 21:14:04.313008

"""

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'message', 'user', ['user_id'], ['id'])
    op.create_foreign_key(None, 'message', 'proposal', ['proposal_id'], ['id'])
    op.create_foreign_key(None, 'participant', 'proposal', ['proposal_id'], ['id'])
    op.create_foreign_key(None, 'participant', 'user', ['user_id'], ['id'])
    op.create_foreign_key(None, 'proposal', 'user', ['cook_user_id'], ['id'])
    op.create_foreign_key(None, 'proposal', 'user', ['proposer_id'], ['id'])
    op.create_foreign_key(None, 'proposal', 'user', ['grocery_user_id'], ['id'])
    op.create_foreign_key(None, 'proposal', 'recipe', ['recipe_id'], ['id'])
    op.create_foreign_key(None, 'recipe', 'user', ['user_id'], ['id'])
    op.create_unique_constraint(None, 'user', ['username'])
    op.create_unique_constraint(None, 'user', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'recipe', type_='foreignkey')
    op.drop_constraint(None, 'proposal', type_='foreignkey')
    op.drop_constraint(None, 'proposal', type_='foreignkey')
    op.drop_constraint(None, 'proposal', type_='foreignkey')
    op.drop_constraint(None, 'proposal', type_='foreignkey')
    op.drop_constraint(None, 'participant', type_='foreignkey')
    op.drop_constraint(None, 'participant', type_='foreignkey')
    op.drop_constraint(None, 'message', type_='foreignkey')
    op.drop_constraint(None, 'message', type_='foreignkey')
    # ### end Alembic commands ###
